//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogAndReg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upload
    {
        public int MemberId { get; set; }
        public string MemberName { get; set; }
        public string PhoneNumber { get; set; }
        public string ImagePath { get; set; }
        public string ImageName { get; set; }
        public Nullable<bool> IsModified { get; set; }
        public string ModifiedName { get; set; }
    }
}
